---
name: Code Coverage

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  go-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2

      - uses: actions/checkout@v3

      - name: Install dependencies for ubuntu-latest
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libgl-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxxf86vm-dev

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: go test -v -covermode=count -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out
