---
name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:

  go-tests:
    name: Go tests
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v3

      - name: Install dependencies for ubuntu-latest
        if: ${{ matrix.os == "ubuntu-latest"}}
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libgl-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxxf86vm-dev

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: go test -v ./...
      