---
name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:

  go-tests:
    name: Go tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install prereqs
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libxcursor-dev libxrandr-dev
      - name: Run Go tests
        run: go test -v ./...
