---
name: Refresh readsb.proto 

on:
  workflow_dispatch:

jobs:

  readsb-protobuf:
    name: Generate go from readsb.proto
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v3

    - uses: actions/checkout@v3

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y libprotobuf-dev protobuf-compiler
        sudo go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

    - name: Fetch latest readsb.proto
      run: |
        set -x
        curl -o ./datasources/readsb.proto https://raw.githubusercontent.com/Mictronics/readsb-protobuf/dev/readsb.proto
    
    - name: Compile readsb.proto into golang
      run: |
        set -x
        find / -type f -iname protoc-gen-go
        export PATH=$PATH:/home/runner/go/bin
        protoc -I=./datasources/ --go_out=./datasources/ readsb.proto
    