---
name: Refresh readsb.proto 

on:
  workflow_dispatch:

jobs:

  readsb-protobuf:
    name: Generate go from readsb.proto
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v3

    - uses: actions/checkout@v3

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y libprotobuf-dev protobuf-compiler
        go install -v google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install -v google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Ensure directory structure exists
      run: |
        set -x
        mkdir -p ./datasources/readsb_protobuf

    - name: Fetch latest readsb.proto
      run: |
        set -x
        curl -o ./datasources/readsb_protobuf/readsb.proto https://raw.githubusercontent.com/Mictronics/readsb-protobuf/dev/readsb.proto
    
    - name: Compile readsb.proto into golang
      run: |
        set -x
        export PATH="$PATH:$(go env GOPATH)/bin"
        protoc -I=./datasources/readsb_protobuf/ --go_out=./datasources/readsb_protobuf/ --go_opt=Mreadsb.proto="./;readsb_protobuf" readsb.proto
        git add ./datasources/readsb_protobuf/readsb.pb.go

    - name: Check for changes
      id: check-changes
      run: |
        set -x
        CHANGES=$(git diff origin/main)
        if [[ -n "$CHANGES" ]]; then
          echo "::set-output name=add_and_commit::true"
        fi 

    - name: Add and commit
      if: steps.check-changes.outputs.add_and_commit == true
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "update of compiled readsb.proto"
        git push
