---
name: Refresh readsb.proto 

on:
  workflow_dispatch:

jobs:

  readsb-protobuf:
    name: Generate go from readsb.proto
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v3

    - uses: actions/checkout@v3

    - name: Install prerequisites
      run: |
        apt-get update
        apt-get install --no-install-recommends -y protoc-gen-go libprotobuf-dev protobuf-compiler

    - name: Fetch latest readsb.proto
      run: |
        set -x
        curl -o ./datasources/readsb.proto https://raw.githubusercontent.com/Mictronics/readsb-protobuf/dev/readsb.proto
    
    - name: Compile readsb.proto into golang
      run: |
        set -x
        protoc -I=./datasources/ --go_out=./datasources/ readsb.proto
    