---
name: Refresh readsb.proto 

on:
  workflow_dispatch:

jobs:

  readsb-protobuf:
    name: Generate go from readsb.proto
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v3

    - uses: actions/checkout@v3

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y libprotobuf-dev protobuf-compiler
        go install -v google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install -v google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Fetch latest readsb.proto
      run: |
        set -x
        echo 'option go_package = "pw_slippymap/datasources";' > ./datasources/readsb.proto
        curl https://raw.githubusercontent.com/Mictronics/readsb-protobuf/dev/readsb.proto >> ./datasources/readsb.proto
    
    - name: Compile readsb.proto into golang
      run: |
        set -x
        export PATH="$PATH:$(go env GOPATH)/bin"
        protoc -I=./datasources/ --go_out=./datasources/--go_opt=Mreadsb.proto="pw_slippymap/datasources" readsb.proto
    